### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by HuangDaohong** [wujihua118/react-admin-client#10]
您好，有一个问题请教您。
react使用browserrouter时候，打包部署到会出现页面无法跳转问题，使用hashRouter时候没有问题，但是不美观，请问您是怎么解决的？谢谢

**Comment by wujihua118** [comment]
我是配置 nginx 反向代理，使用 [try_files 指令](http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files)
```bash
 server {
  ...
  location / {
    try_files $uri /index.html
  }
}
```
